import { Link } from 'react-router-dom'
import { ArrowRight, CalendarDays, CheckCircle2, Clock3, HeartPulse, ShieldCheck, Stethoscope, UsersRound, Star, Quote } from 'lucide-react'

const heroImage = 'https://images.pexels.com/photos/6749765/pexels-photo-6749765.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'
const consultImage = 'https://images.pexels.com/photos/8413162/pexels-photo-8413162.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'
const doctors = [
  { name: 'Dr. Sarah Mitchell', role: 'Chief Medical Officer', image: 'https://images.pexels.com/photos/6749765/pexels-photo-6749765.jpeg?auto=compress&cs=tinysrgb&h=650&w=940' },
  { name: 'Dr. James Wilson', role: 'Cardiology Specialist', image: 'https://images.pexels.com/photos/18788957/pexels-photo-18788957.jpeg?auto=compress&cs=tinysrgb&h=650&w=940' },
  { name: 'Dr. Emily Carter', role: 'Pediatrician', image: 'https://images.pexels.com/photos/19131220/pexels-photo-19131220.jpeg?auto=compress&cs=tinysrgb&h=650&w=940' },
]
const services = [
  { icon: Stethoscope, title: 'General Medicine', text: 'Comprehensive care for your everyday health needs.' },
  { icon: HeartPulse, title: 'Cardiology', text: 'Expert heart care focused on prevention and recovery.' },
  { icon: UsersRound, title: 'Pediatrics', text: 'Gentle, trusted care for your little ones.' },
]

function Home() {
  return <div>
    <section className="overflow-hidden bg-primary-50"><div className="mx-auto grid max-w-7xl items-center gap-12 px-5 py-16 sm:py-20 lg:grid-cols-[1.04fr_.96fr] lg:px-8 lg:py-24"><div className="animate-slide-up"><div className="mb-6 inline-flex items-center gap-2 rounded-full border border-primary-200 bg-white px-3 py-2 text-xs font-bold text-primary-700"><span className="h-2 w-2 rounded-full bg-accent-500" /> Trusted healthcare for your whole family</div><h1 className="max-w-2xl font-heading text-4xl font-bold leading-[1.12] tracking-tight text-primary-950 sm:text-6xl">Your health is our <span className="text-primary-600">priority.</span></h1><p className="mt-6 max-w-xl text-base leading-8 text-slate-600 sm:text-lg">Quality healthcare made simple. Connect with experienced doctors and get the care you deserve, whenever you need it.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link to="/appointment" className="flex items-center justify-center gap-2 rounded-xl bg-primary-600 px-6 py-3.5 text-sm font-bold text-white shadow-xl shadow-primary-600/20 transition hover:-translate-y-0.5 hover:bg-primary-700">Book an Appointment <ArrowRight size={17} /></Link><Link to="/services" className="flex items-center justify-center gap-2 rounded-xl border border-slate-200 bg-white px-6 py-3.5 text-sm font-bold text-slate-700 transition hover:border-primary-300 hover:text-primary-700">Explore Services</Link></div><div className="mt-9 flex items-center gap-6 text-sm text-slate-600"><span className="flex items-center gap-2"><CheckCircle2 className="text-accent-600" size={18} /> Licensed doctors</span><span className="flex items-center gap-2"><CheckCircle2 className="text-accent-600" size={18} /> 24/7 support</span></div></div><div className="relative mx-auto w-full max-w-md lg:ml-auto"><div className="absolute -inset-5 rounded-[2.5rem] bg-primary-100/70" /><img src={heroImage} alt="Smiling doctor ready to help" className="relative h-[480px] w-full rounded-[2rem] object-cover object-top shadow-2xl sm:h-[560px]" /><div className="absolute -bottom-5 -left-4 flex items-center gap-3 rounded-2xl bg-white p-4 shadow-xl sm:-left-8"><span className="flex h-12 w-12 items-center justify-center rounded-xl bg-accent-50 text-accent-600"><ShieldCheck size={25} /></span><div><p className="font-heading text-lg font-bold text-primary-950">98%</p><p className="text-xs text-slate-500">Patient satisfaction</p></div></div><div className="absolute right-3 top-8 rounded-2xl bg-white p-4 shadow-xl sm:-right-5"><div className="flex items-center gap-2"><span className="text-sm font-bold text-primary-950">4.9</span><div className="flex text-amber-400"><Star size={14} fill="currentColor" /><Star size={14} fill="currentColor" /><Star size={14} fill="currentColor" /><Star size={14} fill="currentColor" /><Star size={14} fill="currentColor" /></div></div><p className="mt-1 text-xs text-slate-500">from 2,000+ reviews</p></div></div></div></section>

    <section className="border-b border-slate-100 bg-white"><div className="mx-auto grid max-w-7xl gap-6 px-5 py-8 sm:grid-cols-3 lg:px-8"><div className="flex items-center gap-4"><span className="flex h-12 w-12 items-center justify-center rounded-xl bg-primary-50 text-primary-600"><Clock3 size={23} /></span><div><p className="font-bold text-slate-900">Flexible Hours</p><p className="mt-1 text-sm text-slate-500">Appointments that fit your day</p></div></div><div className="flex items-center gap-4"><span className="flex h-12 w-12 items-center justify-center rounded-xl bg-accent-50 text-accent-600"><UsersRound size={23} /></span><div><p className="font-bold text-slate-900">Expert Doctors</p><p className="mt-1 text-sm text-slate-500">Experienced and compassionate</p></div></div><div className="flex items-center gap-4"><span className="flex h-12 w-12 items-center justify-center rounded-xl bg-amber-50 text-amber-600"><ShieldCheck size={23} /></span><div><p className="font-bold text-slate-900">Trusted Care</p><p className="mt-1 text-sm text-slate-500">Your wellbeing comes first</p></div></div></div></section>

    <section className="mx-auto max-w-7xl px-5 py-20 lg:px-8"><div className="grid items-center gap-12 lg:grid-cols-2"><div className="relative"><img src={consultImage} alt="Doctor consulting with a patient" className="h-[400px] w-full rounded-[2rem] object-cover sm:h-[500px]" /><div className="absolute -bottom-6 -right-4 rounded-2xl bg-white p-5 shadow-xl sm:-right-7"><p className="font-heading text-3xl font-bold text-primary-600">15+</p><p className="mt-1 text-sm text-slate-500">Years of excellence</p></div></div><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-primary-600">Why MediCare+</p><h2 className="mt-3 font-heading text-3xl font-bold leading-tight text-primary-950 sm:text-4xl">Healthcare that puts you first</h2><p className="mt-5 text-base leading-8 text-slate-600">We believe great healthcare starts with listening. Our team combines medical expertise with genuine compassion to create a care experience centered around you.</p><div className="mt-7 space-y-4"><p className="flex gap-3 text-sm font-semibold text-slate-700"><CheckCircle2 className="shrink-0 text-accent-600" size={19} /> Personalized care plans for every patient</p><p className="flex gap-3 text-sm font-semibold text-slate-700"><CheckCircle2 className="shrink-0 text-accent-600" size={19} /> Modern facilities and advanced technology</p><p className="flex gap-3 text-sm font-semibold text-slate-700"><CheckCircle2 className="shrink-0 text-accent-600" size={19} /> A team that truly listens to your needs</p></div><Link to="/about" className="mt-8 inline-flex items-center gap-2 text-sm font-bold text-primary-600 hover:text-primary-800">Discover our story <ArrowRight size={17} /></Link></div></div></section>

    <section className="bg-slate-50"><div className="mx-auto max-w-7xl px-5 py-20 lg:px-8"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-primary-600">What we offer</p><h2 className="mt-3 font-heading text-3xl font-bold text-primary-950 sm:text-4xl">Care for every stage of life</h2></div><Link to="/services" className="flex items-center gap-2 text-sm font-bold text-primary-600">View all services <ArrowRight size={17} /></Link></div><div className="mt-10 grid gap-5 md:grid-cols-3">{services.map(({ icon: Icon, title, text }) => <div key={title} className="rounded-2xl border border-slate-100 bg-white p-7 shadow-sm transition hover:-translate-y-1 hover:shadow-xl"><span className="flex h-12 w-12 items-center justify-center rounded-xl bg-primary-50 text-primary-600"><Icon size={24} /></span><h3 className="mt-6 font-heading text-xl font-bold text-primary-950">{title}</h3><p className="mt-3 text-sm leading-7 text-slate-500">{text}</p><Link to="/services" className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-primary-600">Learn more <ArrowRight size={15} /></Link></div>)}</div></div></section>

    <section className="mx-auto max-w-7xl px-5 py-20 lg:px-8"><div className="text-center"><p className="text-xs font-bold uppercase tracking-[0.2em] text-primary-600">Our specialists</p><h2 className="mt-3 font-heading text-3xl font-bold text-primary-950 sm:text-4xl">Meet the people who care</h2></div><div className="mt-10 grid gap-6 sm:grid-cols-3">{doctors.map((doctor) => <div key={doctor.name} className="overflow-hidden rounded-2xl border border-slate-100 bg-white shadow-sm"><img src={doctor.image} alt={doctor.name} className="h-72 w-full object-cover object-top" /><div className="p-5"><h3 className="font-heading text-lg font-bold text-primary-950">{doctor.name}</h3><p className="mt-1 text-sm text-primary-600">{doctor.role}</p></div></div>)}</div><div className="mt-9 text-center"><Link to="/doctors" className="inline-flex items-center gap-2 rounded-xl border border-primary-200 px-5 py-3 text-sm font-bold text-primary-700 transition hover:bg-primary-50">Meet all doctors <ArrowRight size={16} /></Link></div></section>

    <section className="bg-primary-600"><div className="mx-auto flex max-w-7xl flex-col items-start justify-between gap-7 px-5 py-14 sm:flex-row sm:items-center lg:px-8"><div><h2 className="font-heading text-3xl font-bold text-white">Ready to take care of your health?</h2><p className="mt-2 text-primary-100">Book your appointment today and take the first step.</p></div><Link to="/appointment" className="flex shrink-0 items-center gap-2 rounded-xl bg-white px-6 py-3.5 text-sm font-bold text-primary-700 shadow-lg transition hover:bg-primary-50">Book an Appointment <CalendarDays size={17} /></Link></div></section>
  </div>
}
export default Home
